Сделал Надо подкачаться
htmlacademy-javascript/2338943-kekstagram-30 pull request #11
Opened 2023-11-24 10:01 UTC by constantine-serov

2023-11-24 17:00 UTC, kenakula requested changes

2023-11-24 17:00 UTC, kenakula commented on js/form.js
> +  );
не сможем удалить обработчик события после закрытия модалки

2023-11-24 17:00 UTC, kenakula commented on js/form.js
> +function setFormSubmit (onSucces, onError, evt) {
не пройдет по неймингу обработчика события

2023-11-24 17:00 UTC, kenakula commented on js/form.js
>  const onButtonShowForm = () => {
на 97й строку
loadingFileForm.addEventListener('change', renderLoadedPicture, {once: true});
почему бы не навесить обработчик на инпут один раз и больше его не трогать, он небудет накапливаться и протекать

2023-11-24 17:00 UTC, kenakula commented on js/form.js
>  const onButtonShowForm = () => {
на 115й строке ты снова этот же обработчик навешиваешь. Проще будет его один раз повесить, но без once: true

2023-11-24 17:00 UTC, kenakula commented on js/form.js
> +};
эти две функции кажется получились очень однотипные и большие. Попробуй либо сделать одну универсальную, которая может принимать в себя аргумент, говорящий какое сообщение мы хотим удалить, в идеале еще разбить внутренности на более мелкие функции

2023-11-25 10:37 UTC, constantine-serov commented on js/form.js
>  const onButtonShowForm = () => {
Я думал, что по заданию его нужно удалять при закрытии формы, поэтому нашёл и добавил {once: true} в него, а потом повторное добавление. Теперь удалил это всё.

2023-11-26 08:03 UTC, merged