2.32. Нужно больше функций
htmlacademy-javascript/2338943-kekstagram-30 pull request #2
Opened 2023-10-09 11:58 UTC by constantine-serov

2023-10-09 16:19 UTC, kenakula requested changes
отличная работа! поправь пожалуйста комменты только

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  return string.length <= maxLength;
напоминалка

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  let normalizeString = (srcString.replaceAll(' ', '')).toLowerCase();
здесь можно не оборачивать в скобки выражение перед .toLowerCase()

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +    console.log(i + 'reverseString: ' + reverseString);
в ES6 есть template strings, попробуй их использовать, конкатенация строк через + обычно запрещается

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  for (let i = normalizeString.length - 1; i >= 0 ; i--) {
старайся отбивать блоки кода пустой строкой, чтобы не касалось другого кода рядом, так будет легче читаться. Это про любые блоки, типо, if, for, while, и др.

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  let normalizeString = Number.isNaN(srcString) ? srcString : String(srcString);
normalize это глагол, тут лучше normalized

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  let normalizeString = Number.isNaN(srcString) ? srcString : String(srcString);
либо сделай это функцией и вынеси наружу 😺

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  let normalizeString = Number.isNaN(srcString) ? srcString : String(srcString);
Number.isNaN вернет false и для числа и для строки, они обе не являются NaN, сначала нужно значение попытаться перевести в число, чтобы это сработало, либо использовать глобальную функцию isNan, она сначала пытается перевести в число

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  let normalizeString = Number.isNaN(srcString) ? srcString : String(srcString);
не стесняйся использовать дополнительные промежуточные переменные, важнее понятный код, а не краткость

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  }
не самый лучший кейс для использования switch, обычно он используется, когда нужно выполнить разные действия для разных значений

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  }
ну а раз уж используешь switch case, то считается хорошим тоном использовать завершающее default 😺

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  return +parseInt(outputNumbers);
плюсик можно не использовать, parseInt уже вернет число)

2023-10-09 16:19 UTC, kenakula commented on js/functions.js
> +  }
а как же числа 0 и 9? думаю тз подразумевало включительно от 0 до 9

2023-10-11 11:35 UTC, constantine-serov commented on js/functions.js
> +    console.log(i + 'reverseString: ' + reverseString);
Я забыл удалить консоль :)

2023-10-11 11:37 UTC, constantine-serov commented on js/functions.js
> +  let normalizeString = Number.isNaN(srcString) ? srcString : String(srcString);
Я запутался. Я так понял, что NaN это буквально "Не Номер"; что если аргумент - строка, то вернёт "true", потому что строка не номер.

Можно просто любой аргумент (даже строку) приказать превращать в строку, чтобы потом в цикле проверять каждый кусочек строки?

2023-10-11 11:46 UTC, constantine-serov commented on js/functions.js
> +  }
Какое действие нужно после default, если у меня switch в цикле и мне нужно просто прервать работу switch, чтобы идти к началу цикла?

В материалах было написано, что надо breack или return писать в switch. Но, когда у меня switch в цикле, процессор после первого совпадения данных breack и return заканчивал работу и switch, и цикла. Поэтому я их убрал.

2023-10-11 11:48 UTC, constantine-serov commented on js/functions.js
> +  return +parseInt(outputNumbers);
Да, сначала не поставил parseInt, потом поставил и забыл удалить плюсик. Невнимательный :)

2023-10-11 19:57 UTC, kenakula commented on js/functions.js
> +  let normalizeString = Number.isNaN(srcString) ? srcString : String(srcString);
фактически можно любой аргумент переводить в строку, но выглядит конечно это не очень, как хак.

Смотри, понимаешь верно, тут просто есть небольшое отличие между двумя методами встроенными:
- Number.isNaN - это статический метод встроенного в js класса Number, у него много еще других методов. Конкретно этот проверяет не является ли аргумент NaN, фишка в том, что перед тем как проверить, он не приводит типы.
- isNaN - это глобальный объект, у него такая же задача, но перед тем как проверить не является ли переданный аргумент NaN, он приводит тип, то есть как будто бы за кулисами делает Number(arg). Строка со словом превращается в число, число остается таким же и т.д.
То есть Number.isNaN вернет true только если ему передать NaN
У нас нет возможности проверить через равенство, потому что NaN != NaN по историческим причинам

2023-10-11 20:03 UTC, kenakula commented on js/functions.js
> +  }
после default можно continue, тогда цикл перейдет к следующей итерации, можно break
если у тебя брейк был не в самом конце в default, тогда да, свитч до конца не отрабатывал
понятно что тут default может и не очень нужен, но надо приучить себя его ставить всегда, чтобы не пропустить ошибку
Вместо switchcase можно пока вы не дошли до методов массивов использовать несколько If например, либо на каждой итерации пробовать преобразовать символ в число, если результат не NaN, то тогда пихать его в строку результирующую.

2023-10-12 18:45 UTC, merged